apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-sensors
  description: Spring Sensors Demo
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors'
    'backstage.io/source-location': 'url:https://github.com/tanzu-end-to-end/spring-sensors/'
spec:
  type: service
  lifecycle: experimental
  owner: tracyde
